stages:
    - build

build_it_debian:
    image: debian:8
    stage: build
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - apt-get update
        - apt-get -y install build-essential clang curl libbz2-dev libgl1-mesa-dev libusb-1.0-0-dev pkg-config
        - ./build-deps.sh -cmake
    tags:
        - build
        - linux

build_it_osx:
    stage: build
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - ./build-deps.sh -cmake -universal
    tags:
        - prebuilt
        - osx

build_it_osx_deploy:
    stage: build
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - ./build-deps.sh -cmake -universal
    tags:
        - deploy
        - osx