stages:
  - build
  - collect
  - deploy

.build:
  variables:
    EXTRA_CMAKE_FLAGS: ""
  before_script:
    - export CMAKE_CMD="cmake -GNinja -DCMAKE_BUILD_TYPE=Release $EXTRA_CMAKE_FLAGS .."
  script:
      - mkdir -p build/
      - cd build/
      - $CMAKE_CMD
      - ninja

build:debian:11:static:
    extends: .build
    stage: build
    image: volcart/vcbuilder-debian:11_v1.base
    needs: []
    tags:
        - docker

build:debian:11:dynamic:
    extends: .build
    stage: build
    image: volcart/vcbuilder-debian:11_v1.base
    needs: []
    variables:
      EXTRA_CMAKE_FLAGS: "-DBUILD_SHARED_LIBS=ON"
    tags:
        - docker

build:macos:static:
    extends: .build
    stage: build
    needs: []
    tags:
        - deploy
        - macos

build:macos:dynamic:
    extends: .build
    stage: build
    needs: []
    variables:
      EXTRA_CMAKE_FLAGS: "-DBUILD_SHARED_LIBS=ON"
    tags:
        - deploy
        - macos

collect:macos:universal:
    extends: .build
    stage: collect
    needs: []
    variables:
      MACOSX_DEPLOYMENT_TARGET: "11.3"
      EXTRA_CMAKE_FLAGS: "-DBUILD_UNIVERSAL_LIBS=ON"
    artifacts:
      name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
      paths:
        - deps/
      expire_in: 1 day
    tags:
        - deploy
        - macos
