stages:
    - dynamic
    - static

build:debian:static:
    image: volcart/vcbuilder-debian:9_v4.base
    stage: static
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        - ninja
    tags:
        - build
        - linux

build:debian:dynamic:
    image: volcart/vcbuilder-debian:9_v4.base
    stage: dynamic
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
        - ninja
    tags:
        - build
        - linux

build:macos:static:
    stage: static
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        - ninja
    tags:
        - homebrew
        - osx

build:macos:dynamic:
    stage: dynamic
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
        - ninja
    tags:
        - homebrew
        - osx

build:macos:universal:
    stage: static
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIVERSAL_LIBS=ON ..
        - ninja
    tags:
        - deploy
        - osx
