stages:
  - build
  - collect
  - deploy

.build:
  variables:
    EXTRA_CMAKE_FLAGS: ""
  before_script:
    - export CMAKE_CMD="cmake -GNinja -DCMAKE_BUILD_TYPE=Release $EXTRA_CMAKE_FLAGS .."
  script:
      - mkdir -p build/
      - cd build/
      - $CMAKE_CMD
      - ninja

build:debian:11:static:
    extends: .build
    stage: build
    image: ghcr.io/educelab/ci-docker:11_v2.base
    needs: []
    tags:
        - docker

build:debian:11:dynamic:
    extends: .build
    stage: build
    image: ghcr.io/educelab/ci-docker:11_v2.base
    needs: []
    variables:
      EXTRA_CMAKE_FLAGS: "-DBUILD_SHARED_LIBS=ON"
    tags:
        - docker

build:macos:static:
    extends: .build
    stage: build
    needs: []
    tags:
        - deploy
        - macos

build:macos:dynamic:
    extends: .build
    stage: build
    needs: []
    variables:
      EXTRA_CMAKE_FLAGS: "-DBUILD_SHARED_LIBS=ON"
    tags:
        - deploy
        - macos
