option(VCDEPS_BUILD_PNG "Build libpng" ${BUILD_MACOS_MULTIARCH})

if(VCDEPS_BUILD_PNG)

set(PNG_SHARED ${BUILD_SHARED_LIBS})
set(PNG_STATIC ON)
if(PNG_SHARED)
  set(PNG_STATIC OFF)
endif()
set(PNG_GLOBAL_CMAKE_ARGS ${GLOBAL_CMAKE_ARGS})
if(BUILD_MACOS_MULTIARCH)
  list(REMOVE_ITEM PNG_GLOBAL_CMAKE_ARGS "-DCMAKE_OSX_ARCHITECTURES:STRING=x86_64;arm64")
  list(APPEND PNG_GLOBAL_CMAKE_ARGS "-DCMAKE_OSX_ARCHITECTURES:STRING=arm64;x86_64")
endif()

externalproject_add(
    libpng
    DEPENDS zlib ${GLOBAL_DEPENDS}
    URL https://github.com/pnggroup/libpng/archive/e4a31f024b6158aaaf55a43502f574d5f5d1c894.tar.gz
    URL_HASH SHA512=cc8ebe4b806b7f4e8b2b90b9ca1a997bc44731e568d06dcbebd8682350ac636c0f72d659eb2aa416bad1423795ea3d45ae338aa7c44e86f0e2d55475fba6366f
    DOWNLOAD_NO_PROGRESS true
    DOWNLOAD_EXTRACT_TIMESTAMP ON
    PATCH_COMMAND ${PNG_PATCH_CMD}
    CMAKE_CACHE_ARGS
        ${PNG_GLOBAL_CMAKE_ARGS}
        -DPNG_TESTS:BOOL=OFF
        -DPNG_TOOLS:BOOL=ON
        -DPNG_HARDWARE_OPTIMIZATIONS:BOOL=OFF
        -DPNG_FRAMEWORK:BOOL=OFF
        -DPNG_SHARED:BOOL=${PNG_SHARED}
        -DPNG_STATIC:BOOL=${PNG_STATIC}
)
else()
  # Nothing to do. OpenCV will build it.
  add_custom_target(libpng)
endif()
